vars: {
    d2-config: {
      theme-overrides: {
        B1: "#FFFFFF"
        N2: "#FFFFFF"
      }
    }
  }
  style: {
    fill: "#111111"
    stroke: "#FFFFFF"
  }
  x: {
    shape: circle
    style: {
      stroke: "#FFFFFF"
    }
  }
  y: {
    shape: circle
    style: {
      stroke: "#FFFFFF"
    }
  }
  
  x -> y: 1.7
  